kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "avp/data/test"
    reloader.stakater.com/auto: "true"
type: Opaque
stringData:
  sample-secret: <sample>