apiVersion: v1
kind: Pod
metadata:
  name: vault-demo
  labels:
    name: vault-demo
spec:
  volumes:
    - name: vault-secret
      secret:
        secretName: example-secret
  containers:
  - name: vault-demo
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: vault-secret
        readOnly: true
        mountPath: "/tmp/test.yaml"
